FROM php:8.2-cli

# Instala dependências do sistema e extensões PHP
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    netcat-openbsd \
    mariadb-client \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql zip gd exif

# Habilita a extensão exif
RUN docker-php-ext-enable exif

# Instala o Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Adiciona wait-for-it ao container
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

# Copia os arquivos pro container
COPY . .

# Instalando as dependências do Laravel
RUN composer install --no-dev --optimize-autoloader

# Copia o script de entrada que vai aguardar o banco
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Define o script de entrada para aguardar o banco e iniciar o servidor
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]