FROM php:8.2-cli

# Instala dependências do sistema e extensões PHP
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    netcat-openbsd \
    mariadb-client \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-install pdo_mysql zip

# Instala o Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copia os arquivos pro container
COPY . .

# Instalando as dependências do Laravel
RUN composer install --no-dev --optimize-autoloader

# Inicialização do container
CMD php artisan serve --host=0.0.0.0 --port=8000